name: build
on: [push, pull_request]

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel 2

      - name: Smoke test (hash-only)
        if: matrix.os != 'windows-latest'
        run: |
          ./build/mars --hash-only | tee out.txt
          grep -E "^STATE_HASH [0-9A-F]{16}$" out.txt

      - name: Smoke test (hash-only) [Windows]
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $out = & .\build\Release\mars.exe --hash-only
          $out
          if ($out -notmatch '^STATE_HASH [0-9A-F]{16}$') { throw "STATE_HASH not found" }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mars-${{ runner.os }}
          path: |
            build/Release/mars.exe
            build/mars
