name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # ---- Configure ----
      # Use the right generator per-OS.
      - name: Configure (Windows, MSBuild)
        if: runner.os == 'Windows'
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Configure (macOS/Linux, single-config)
        if: runner.os != 'Windows'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      # ---- Build (cross-platform parallelism) ----
      - name: Build
        run: cmake --build build --config Release --parallel 2

      # ---- Upload artifacts ----
      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: mars_colony-${{ runner.os }}
          path: build/Release/mars_colony.exe

      - name: Upload artifact (macOS/Linux)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: mars_colony-${{ runner.os }}
          path: build/mars_colony
