name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up C++
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ clang
      - name: Build
        shell: bash
        run: |
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then CXX=clang++; else CXX=g++; fi
          $CXX -std=c++17 -O2 -Wall -Wextra -o mars mars_colony.cpp
      - name: Self-test
        shell: bash
        run: ./mars --selftest
